export const sampleCards = [
  {
    slug: 'red',
    name: '答えをください',
    author: 'dog',
    cover: '/',
    published: '202x-xx-01',
    tags: ['notion', 'nextjs'],
    content: 'Red page content',
    category: 'test',
  },
  {
    slug: 'green',
    name: 'もう疲れたの',
    author: 'cat',
    cover: '/',
    published: '202x-xx-02',
    tags: ['notion'],
    content: 'Green page content',
    category: 'test2',
  },
  {
    slug: 'blue',
    name: '予感',
    author: 'bird',
    cover: '/',
    published: '202x-xx-03',
    tags: ['react'],
    content: 'Blue page content',
    category: 'test3',
  },
  {
    slug: 'test1',
    name: '寝ても覚めても眠い',
    author: 'dog',
    cover: '/',
    published: '202x-xx-01',
    tags: ['notion', 'nextjs'],
    content: 'Red page content',
    category: 'test',
  },
  {
    slug: 'test2',
    name: 'あれだけ言ったのに',
    author: 'cat',
    cover: '/',
    published: '202x-xx-02',
    tags: ['notion'],
    content: 'Green page content',
    category: 'test2',
  },
  {
    slug: 'test3',
    name: '文字が長すぎたらどうするのだという件について',
    author: 'bird',
    cover: '/',
    published: '202x-xx-03',
    tags: ['react'],
    content: 'Blue page content',
    category: 'test3',
  },
];
